name: CI/CD for OWASP Juice Shop

on:
  push:
    branches:
      - master

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript,typescript

      - name: Perform CodeQL Analysis (SAST)
        uses: github/codeql-action/analyze@v2

  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Snyk Vulnerability Scan (SCA)
        uses: snyk/actions@v1
        with:
          args: test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk Report
        if: failure() || success()
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk_report.json

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [sast, sca]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull Docker Image
        run: docker pull bkimminich/juice-shop

      - name: Deploy Application
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop

  dast:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Run OWASP ZAP (DAST)
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:3000
